#!/usr/bin/env bash

digitalocean_parse_params()
{
  while
    (( $# > 0 ))
  do
    token="$1"
    shift
    case "$token" in

      (--path)
        if [[ -n "${1:-}" ]]
        then
          digitalocean_path="$1"
          shift
        else
          fail "--path must be followed by a path, e.g. /usr/local/bin."
        fi
        ;;

      (--dog)
        if [[ -n "${1:-}" ]]
        then
          digitalocean_filename="$1"
          shift
        else
          fail "--dog must be followed by a filename, e.g. /usr/local/bin/dog"
        fi
        ;;


    esac
  done

  digitalocean_path=${digitalocean_path-/usr/local/bin}
  digitalocean_filename=${digitalocean_filename-${digitalocean_path}/dog}
}

do_install()
{
  digitalocean_parse_params "$@"
  echo "Installing dog into \"$digitalocean_filename\""
  curl -s -o "$digitalocean_filename" https://raw.githubusercontent.com/capbash/dog/master/dog
  chmod 755 "${digitalocean_filename}"
  echo "Done, to uninstall 'rm \"${digitalocean_filename}\"'."
}

do_install "$@"